all:
	g++ pager.cc -o pager libvm_pager.a -w -ldl -std=c++11

test0:
	g++ test0.2.cc -o test0 libvm_app.a -w -ldl -std=c++11

test1:
	g++ test1.2.cc -o test1 libvm_app.a -w -ldl -std=c++11

test2:
	g++ test2.2.cc -o test2 libvm_app.a -w -ldl -std=c++11

test3:
	g++ test3.2.cc -o test3 libvm_app.a -w -ldl -std=c++11

test4:
	g++ test4.2.cc -o test4 libvm_app.a -w -ldl -std=c++11

test5:
	g++ test5.2.cc -o test5 libvm_app.a -w -ldl -std=c++11

test6:
	g++ test6.2.cc -o test6 libvm_app.a -w -ldl -std=c++11

test7:
	g++ test7.2.cc -o test7 libvm_app.a -w -ldl -std=c++11

test8:
	g++ test8.2.cc -o test8 libvm_app.a -w -ldl -std=c++11

test9:
	g++ test9.2.cc -o test9 libvm_app.a -w -ldl -std=c++11

test10:
	g++ test10.2.cc -o test10 libvm_app.a -w -ldl -std=c++11

test11:
	g++ test11.2.cc -o test11 libvm_app.a -w -ldl -std=c++11

test12:
	g++ test12.2.cc -o test12 libvm_app.a -w -ldl -std=c++11

test13:
	g++ test13.2.cc -o test13 libvm_app.a -w -ldl -std=c++11

test14:
	g++ test14.2.cc -o test14 libvm_app.a -w -ldl -std=c++11

test15:
	g++ test15.2.cc -o test15 libvm_app.a -w -ldl -std=c++11

test16:
	g++ test16.2.cc -o test16 libvm_app.a -w -ldl -std=c++11

test17:
	g++ test17.2.cc -o test17 libvm_app.a -w -ldl -std=c++11

test18:
	g++ test18.2.cc -o test18 libvm_app.a -w -ldl -std=c++11

test19:
	g++ test19.2.cc -o test19 libvm_app.a -w -ldl -std=c++11

clean:
	rm pager test0 test1 test2 test3 test4 test5 test6 test7 test8 test9 test10 test11 test12 test13 test14 test15 test16 test17 test18 test19

